### ISSUE TITLE
[FEATURE REQUEST] Add support for nested mapping

### ISSUE THREAD

**Issue by yantosca** [yantosca/qfyaml#2]
At present qfyaml can only read from YAML files with one level of mapping, i.e.
```
category:
  key1: value1
  key2: value2
```
but it cannot handle nested categories,i.e.
```
category:
  nested_category:
    key1: value1
    key2: value2
```
This would be a useful feature to have.  It should be theoretically easy to extend the category name.  We will try to add this feature as time allows.
